name: App Builder

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Frontend
      if: github.event_name != 'pull_request'
      run: echo y | ./scripts/build_frontend.sh
      
    - name: Build Binary
      run: echo y |./scripts/build_binary.sh
         
    - name: Build Packages
      if: github.event_name != 'pull_request'
      run: |
          sed -i 's|goreleaser/nfpm|goreleaser/nfpm|g' scripts/build_package.sh
          RELEASE=$(./homer-app -version | egrep -o '[0-9].[0-9].[0-9]+')
          echo "TAG_NAME=$RELEASE" >> $GITHUB_ENV
          VERSION=$RELEASE make package
          
    - name: Archive Frontend
      if: github.event_name != 'pull_request'
      run: tar cvfz homer-ui-${{env.TAG_NAME}}.tgz dist

            
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: 712120393/webapp:latest
